name: Attribution check

on:
  push: {}
  pull_request: {}

jobs:
  check-attribution:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Run attribution check
        run: node ./scripts/check_attribution.js
